name: Python application
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyinstaller
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
      shell: pwsh
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Package Application
      run: |
        cd src
        pyinstaller --onefile --name docker-dev-lamp-${{ runner.os }} docker-dev-lamp-env.py
    - uses: actions/upload-artifact@v2
      with:
        name: docker-dev-lamp-${{ runner.os }}
        path: src/dist/*

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Tag
      id: create_tag
      run: |
        VERSION=$(date +"%Y%m%d%H%M%S")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        git tag $VERSION
        git push origin $VERSION
    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRET_TOKEN }}
