name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: docker-dev-lamp-linux
        path: src/dist/linux

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: docker-dev-lamp-windows
        path: src/dist/windows

    - name: Create Tag
      id: create_tag
      run: |
        VERSION=$(date +"%Y%m%d%H%M%S")
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        git tag $VERSION
        git push origin $VERSION

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src/dist/linux/**/*
          src/dist/windows/**/*
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_SECRET_TOKEN }}
